/// Una voce del glossario: termine + definizione semplice.
class GlossaryTerm {
  const GlossaryTerm(this.term, this.definition);
  final String term;
  final String definition;
}

/// Glossario dei termini finanziari spiegati in modo semplice (educativo).
const glossaryTerms = <GlossaryTerm>[
  GlossaryTerm('Azione',
      'Una quota di proprietà di un\'azienda. Chi la possiede partecipa ai profitti (dividendi) e alle oscillazioni del valore.'),
  GlossaryTerm('Obbligazione',
      'Un prestito a uno stato o a un\'azienda che in cambio paga interessi e restituisce il capitale a scadenza. Più stabile dell\'azione.'),
  GlossaryTerm('ETF',
      'Un fondo quotato che replica un indice (es. l\'MSCI World). Con un solo strumento compri tanti titoli: diversificazione a basso costo.'),
  GlossaryTerm('Indice',
      'Un paniere che misura l\'andamento di un mercato o settore (es. S&P 500, FTSE MIB). Gli ETF spesso lo replicano.'),
  GlossaryTerm('PAC (Piano di Accumulo)',
      'Versare una cifra fissa a intervalli regolari. Compri un po\' alla volta senza dover indovinare il momento giusto.'),
  GlossaryTerm('Diversificazione',
      'Distribuire i soldi su strumenti che non si muovono tutti insieme, per ridurre il rischio complessivo.'),
  GlossaryTerm('TER',
      'Total Expense Ratio: il costo annuo di un fondo/ETF, in percentuale. A parità di indice, più basso è meglio.'),
  GlossaryTerm('ACC / DIST',
      'Un ETF ad Accumulazione (ACC) reinveste i dividendi da solo; a Distribuzione (DIST) te li paga. ACC per far crescere, DIST per una rendita.'),
  GlossaryTerm('ISIN',
      'Il codice internazionale che identifica in modo univoco uno strumento finanziario (12 caratteri).'),
  GlossaryTerm('Ribilanciamento',
      'Riportare le percentuali del portafoglio ai valori obiettivo quando si sono spostate, meglio se con i nuovi versamenti.'),
  GlossaryTerm('Volatilità',
      'Quanto oscilla il prezzo: alta volatilità = sali e scendi ampi. Non è "il rischio", ma ne è un\'indicazione.'),
  GlossaryTerm('Interesse composto',
      'I rendimenti generano a loro volta rendimenti. Su orizzonti lunghi è la forza più potente per l\'investitore.'),
  GlossaryTerm('Orizzonte temporale',
      'Per quanti anni lasci lavorare l\'investimento. Più lungo, più le oscillazioni hanno modo di compensarsi.'),
  GlossaryTerm('Capital gain',
      'La plusvalenza: il guadagno realizzato vendendo a un prezzo superiore a quello d\'acquisto. In Italia è tassato (spesso al 26%).'),
  GlossaryTerm('Dividendo',
      'La quota di utili che un\'azienda (o un fondo) distribuisce a chi detiene le sue azioni/quote.'),
  GlossaryTerm('Rendimento',
      'Quanto ha reso un investimento, in percentuale, in un periodo. Può essere da prezzo e/o da dividendi.'),
  GlossaryTerm('Lazy portfolio',
      'Un portafoglio "pigro": un\'allocazione semplice e diversificata da mantenere nel tempo (es. 60/40, all-world).'),
  GlossaryTerm('Asset class',
      'Una categoria di strumenti con caratteristiche simili: azioni, obbligazioni, liquidità, oro…'),
  GlossaryTerm('Liquidità',
      'La facilità con cui compri/vendi uno strumento senza spostarne il prezzo; anche la parte di portafoglio in contanti.'),
  GlossaryTerm('P/E (Prezzo/Utili)',
      'Rapporto tra prezzo dell\'azione e utili per azione: quante volte gli utili stai pagando. Utile per confrontare valutazioni.'),
  GlossaryTerm('Valore intrinseco',
      'Quanto "vale davvero" un\'azienda secondo una stima (es. flussi di cassa attualizzati), al netto del prezzo di mercato.'),
  GlossaryTerm('Margine di sicurezza',
      'La distanza tra prezzo pagato e valore intrinseco stimato: protegge dagli errori di stima (spesso ~20-40%).'),
  GlossaryTerm('Value investing',
      'Approccio che compra titoli scambiati sotto il loro valore intrinseco, con pazienza e margine di sicurezza (Graham, Buffett).'),
  GlossaryTerm('Behavior gap',
      'La differenza tra il rendimento del mercato e quello che l\'investitore medio ottiene, erosa da errori comportamentali.'),
  GlossaryTerm('Panic selling',
      'Vendere in preda alla paura durante un ribasso: uno degli errori più costosi, perché cristallizza le perdite.'),
  GlossaryTerm('Leva finanziaria',
      'Esposizione amplificata (es. 2x): moltiplica guadagni e perdite. Aumenta molto il rischio.'),
  GlossaryTerm('Benchmark',
      'Il riferimento con cui confronti il tuo rendimento (es. un indice). Serve a capire se stai facendo meglio o peggio del mercato.'),
  GlossaryTerm('Drawdown',
      'La perdita massima da un picco a un minimo successivo. Misura "quanto male" è andata nel periodo peggiore.'),
];
